#!/bin/bash

# These commands are not tested to work well cross platform.
# View them as convenient suggestions, not exact answers.

REPO_NAME=letharion-dot-files
git clone --recursive git@github.com:letharion/${REPO_NAME}.git

cd letharion-dot-files
git clone git://github.com/altercation/vim-colors-solarized.git
mv vim-colors-solarized dot-vim/.vim/bundle/

if [[ -L ~/.vimrc-custom || ! -f ~/.vimrc-custom ]]; then
  echo "Creating symbolic link ~/.vimrc-custom to $(pwd)/vimrc-custom"
  ln -s $(pwd)/vimrc-custom ~/.vimrc-custom
else
  echo "Skipping link to vimrc-custom as there is a non symlink file there already."
fi

if [[ -L ~/.vimrc || ! -f ~/.vimrc ]]; then
  echo "Creating symbolic link ~/.vimrc to $(pwd)/vimrc"
  ln -s $(pwd)/dot-vim/.vimrc ~/.vimrc
else
  echo "~/.vimrc already exists, and is not a symlink. Please remove or move."
  exit 1
fi

if [[ -L ~/.vim || ! -d ~/.vim ]]; then
  echo "Creating symbolic link ~/.vim to $(pwd)/dotvim"
  ln -s $(pwd)/dot-vim/.vim ~/.vim
else
   echo "~/.vim already exists, and is not a symlink. Please remove or move."
  exit 1
fi

wget http://pear2.php.net/pyrus.phar
php pyrus.phar install pear/PHP_CodeSniffer

# (or pear install PHP_CodeSniffer)
# as well as the actual Drupal coding standard

cd ~/.vim
drush dl coder
# Assuming your pear is installed in /usr/lib/php
ln -sv /usr/lib/php/pear/ ~/.vimdir/coder/coder_sniffer/Drupal
